/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qgjkjyiqgelbsfwoflcg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnamtqeWlxZ2VsYnNmd29mbGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyODM5NzAsImV4cCI6MjA4ODg1OTk3MH0.jILY9c2Cy1F-rN1SU3pk-rlWJNvLxC_iwzReBDyAMVs"